CONNECT SYSTEM/123123@localhost:1521/XEPDB1

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';


CREATE TABLE aluno (
    cpf VARCHAR2(11) PRIMARY KEY,     
    nome VARCHAR2(100) NOT NULL,     
    email VARCHAR2(100) NOT NULL,    
    senha VARCHAR2(255) NOT NULL,     
    telefone VARCHAR2(19) NOT NULL,   
    plano VARCHAR2(50) NOT NULL       
);

CREATE TABLE frequencia (
    id_frequencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
    cpf_aluno VARCHAR2(11) NOT NULL,           
    entrada TIMESTAMP NOT NULL,                
    saida TIMESTAMP,                  
    CONSTRAINT fk_aluno FOREIGN KEY (cpf_aluno) REFERENCES aluno(cpf)
    ON DELETE CASCADE
);


CREATE TABLE administradores (
    ID_admin NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50),
    email VARCHAR2(50) UNIQUE,
    senha VARCHAR2(100)
);

DROP TABLE alunos;
DROP TABLE frequencia;
DROP TABLE administradores;
DROP TABLE relatorio;

INSERT INTO aluno (cpf, nome, email, senha, telefone, plano)
VALUES 
('23951425814', 'Matias Amma', 'matiasamma@gmail.com', '$2b$10$5spzF2Ofx8Yy5Bemktm9Q.oNHXkACjG77yBvuQMqcuZXVlQDCXtce9', '19981713212', 'Mensal');

INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES

('23951425814', TO_TIMESTAMP('2024-12-04 01:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-04 09:30:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO administradores (nome, email, senha)
VALUES
('Admin', 'admin@gmail.com', '$2b$10$5spzF2Ofx8Yy5Bemktm9Q.oNHXkACjG77yBvuQMqcuZXVlQDCXtce');
-- Inserindo Alunos
INSERT INTO aluno (cpf, nome, email, senha, telefone, plano)
VALUES ('12345678901', 'João Silva', 'joao@gmail.com', '$2b$10$senhaSegura1', '11999999991', 'Mensal');

INSERT INTO aluno (cpf, nome, email, senha, telefone, plano)
VALUES ('98765432109', 'Maria Oliveira', 'maria@gmail.com', '$2b$10$senhaSegura2', '11999999992', 'Semestral');

INSERT INTO aluno (cpf, nome, email, senha, telefone, plano)
VALUES ('15975345685', 'Carlos Pereira', 'carlos@gmail.com', '$2b$10$senhaSegura3', '11999999993', 'Mensal');

INSERT INTO aluno (cpf, nome, email, senha, telefone, plano)
VALUES ('75395125874', 'Ana Costa', 'ana@gmail.com', '$2b$10$senhaSegura4', '11999999994', 'Anual');

INSERT INTO aluno (cpf, nome, email, senha, telefone, plano)
VALUES ('45678912310', 'Paulo Souza', 'paulo@gmail.com', '$2b$10$senhaSegura5', '11999999995', 'Semestral');
-- João silva iniciante --
INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('12345678901', TO_TIMESTAMP('2024-12-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('12345678901', TO_TIMESTAMP('2024-12-03 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-03 10:30:00', 'YYYY-MM-DD HH24:MI:SS'));

-- Maria Oliveira (Intermediário - De 6 a 10 horas semanais)
INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('98765432109', TO_TIMESTAMP('2024-12-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('98765432109', TO_TIMESTAMP('2024-12-03 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-03 12:30:00', 'YYYY-MM-DD HH24:MI:SS'));

-- Carlos Pereira (Avançado - De 11 a 20 horas semanais)
INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('15975345685', TO_TIMESTAMP('2024-12-01 07:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('15975345685', TO_TIMESTAMP('2024-12-03 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-03 15:30:00', 'YYYY-MM-DD HH24:MI:SS'));

-- Ana Costa (Extremamente Avançado - Acima de 20 horas semanais)
INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('75395125874', TO_TIMESTAMP('2024-12-01 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-01 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('75395125874', TO_TIMESTAMP('2024-12-02 07:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-02 19:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('75395125874', TO_TIMESTAMP('2024-12-03 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-03 14:30:00', 'YYYY-MM-DD HH24:MI:SS'));

-- Paulo Souza (Mais de 10 horas mas menos que 20)
INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('45678912310', TO_TIMESTAMP('2024-12-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-01 12:30:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO frequencia (cpf_aluno, entrada, saida)
VALUES ('45678912310', TO_TIMESTAMP('2024-12-03 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-03 18:30:00', 'YYYY-MM-DD HH24:MI:SS'));
